//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanitarianAid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminDetail
    {
        public int A_id { get; set; }
        public string A_name { get; set; }
        public string A_mail { get; set; }
        public string A_pass { get; set; }
        public string A_gender { get; set; }
        public Nullable<System.DateTime> A_DOB { get; set; }
        public string A_address { get; set; }
        public Nullable<int> A_phoneNo { get; set; }
    }
}
