//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanitarianAid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appeal
    {
        public int AppealId { get; set; }
        public Nullable<int> N_id { get; set; }
        public string Productname { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Unit { get; set; }
        public string Story { get; set; }
        public string Status { get; set; }
    }
}
