//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanitarianAid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donationtable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Donationtable()
        {
            this.Donationdetails = new HashSet<Donationdetail>();
            this.Records = new HashSet<Record>();
            this.Requests = new HashSet<Request>();
        }
    
        public int Productid { get; set; }
        public string Producttype { get; set; }
        public string Productname { get; set; }
        public decimal Quantity { get; set; }
        public string Unit { get; set; }
        public System.DateTime DateOfDonation { get; set; }
        public int D_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donationdetail> Donationdetails { get; set; }
        public virtual DonorDetail DonorDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Record> Records { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Requests { get; set; }
    }
}
