//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanitarianAid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donorrating
    {
        public int D_ID { get; set; }
        public int DonorRatings { get; set; }
    
        public virtual DonorDetail DonorDetail { get; set; }
    }
}
