//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanitarianAid.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DonorDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonorDetail()
        {
            this.Donationdetails = new HashSet<Donationdetail>();
            this.Donationtables = new HashSet<Donationtable>();
            this.DonationCounts = new HashSet<DonationCount>();
            this.Donorratings = new HashSet<Donorrating>();
            this.Records = new HashSet<Record>();
            this.Requests = new HashSet<Request>();
        }



        [Display(Name = "ID")]
        public int D_id { get; set; }
        [Required]


        [DataType(DataType.Text)]
        [Display(Name = "Name")]

        public string D_name { get; set; }
        [Required]

        [DataType(DataType.EmailAddress)]
        [Display(Name = "Email")]

        public string D_mail { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]

        public string D_Password { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "ConfirmPassword")]
        [Compare("D_Password", ErrorMessage = "Password and Confirm Password mismatched")]


        public string D_ConfirmPassword { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "DateOfBirth")]



        public string D_dob { get; set; }


        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Age")]


        public int D_age { get; set; }

        [Required]
        [DataType(DataType.Currency)]
        [Display(Name = "AnnualIncome")]



        public int D_annualincome { get; set; }


        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "gender")]


        public string D_gender { get; set; }


        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Address")]

        public string D_address { get; set; }

        [Required]
        [DataType(DataType.PhoneNumber)]
        [Display(Name = "PhoneNo")]

        public int D_phoneNo { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Nationality")]

        public string D_nationality { get; set; }


        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Occupation")]

        public string D_occupation { get; set; }















        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donationdetail> Donationdetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donationtable> Donationtables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonationCount> DonationCounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donorrating> Donorratings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Record> Records { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Requests { get; set; }
    }
}
