//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanitarianAid.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HumanitarianAidEntities : DbContext
    {
        public HumanitarianAidEntities()
            : base("name=HumanitarianAidEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminDetail> AdminDetails { get; set; }
        public virtual DbSet<Donationdetail> Donationdetails { get; set; }
        public virtual DbSet<Donationtable> Donationtables { get; set; }
        public virtual DbSet<DonorDetail> DonorDetails { get; set; }
        public virtual DbSet<LogInAdmin> LogInAdmins { get; set; }
        public virtual DbSet<NeedyDetail> NeedyDetails { get; set; }
        public virtual DbSet<Record> Records { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<DonationCount> DonationCounts { get; set; }
        public virtual DbSet<Donorrating> Donorratings { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
        public virtual DbSet<Appeal> Appeals { get; set; }
        public virtual DbSet<Donation> Donations { get; set; }
        public virtual DbSet<Records1> Records1 { get; set; }
        public virtual DbSet<DonorActivation> DonorActivations { get; set; }
        public virtual DbSet<NeedyActivation> NeedyActivations { get; set; }
    }
}
