//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanitarianAid.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NeedyDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NeedyDetail()
        {
            this.Records = new HashSet<Record>();
            this.Requests = new HashSet<Request>();
        }


        [Display(Name= "ID")]
        public int N_id { get; set; }

        [Required]


        [DataType(DataType.Text)]
        [Display(Name = "Name")]
        public string N_name { get; set; }

        [Required]

        [DataType(DataType.EmailAddress)]
        [Display(Name = "Email")]


        public string N_mail { get; set; }
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]



        public string N_Password { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]



        public string N_ConfirmPassword { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "DateOfBirth")]




        public string N_dob { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Age")]





        public int N_age { get; set; }

        [Required]
        [DataType(DataType.Currency)]
        [Display(Name = "AnnualIncome")]





        public int N_annualincome { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "gender")]


        public string N_gender { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Address")]



        public string N_address { get; set; }

        [Required]
        [DataType(DataType.PhoneNumber)]
        [Display(Name = "PhoneNo")]


        public int N_phoneNo { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Nationality")]


        public string N_nationality { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Occupation")]


        public string N_occupation { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Record> Records { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Requests { get; set; }
    }
}
