//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanitarianAid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int SL { get; set; }
        public int D_ID { get; set; }
        public int N_ID { get; set; }
        public int P_ID { get; set; }
        public string R_ProductName { get; set; }
        public decimal Quantity { get; set; }
        public string unit { get; set; }
    
        public virtual Donationtable Donationtable { get; set; }
        public virtual DonorDetail DonorDetail { get; set; }
        public virtual NeedyDetail NeedyDetail { get; set; }
    }
}
